### ISSUE TITLE
Fix the link modal

### ISSUE THREAD

**Issue by dianabit** [citizensadvice/react-rich-text-editor#25]
The link modal is commented out and not working currently because it was initially developed to use a Casebook component for the dialog. Now, we don't have access to the component anymore.

We need to add an individual component for the dialog that behaves the same as the one in Casebook.

**Comment by mrdaniellewis** [comment]
I've started trying to move the dialog into a separate repository

**Comment by dianabit** [comment]
That's great news!

However, I assume it will be a while until that is ready to be used and I am worried that we will need to use a dialog in this repository sooner than that.

So I think we still need to find a temporary solution?
