### ISSUE TITLE
Remove the validation

### ISSUE THREAD

**Issue by mrdaniellewis** [citizensadvice/react-rich-text-editor#9]
The consumer should be responsible for any validation, so the hidden text area validation isn't needed in this package.

This package should allow `aria-invalid` and `aria-describedby` attributes to be passed to the `<Editor>` so it can mark it invalid and associate it with a validation message.

**Comment by dianabit** [comment]
@mrdaniellewis the slate.js Editor does not contain an `input` element at its core, only `span` and `div`, so this makes it difficult to allow `aria-invalid `and `aria-describedby` attributes.
What would be a best solution in this case?

I was thinking either to have a **hidden input** that holds these attributes or leave the **textarea** only for this purpose, removing any other events that happen on it.

**Comment by mrdaniellewis** [comment]
That's fine, so it outputs as `<div contenteditable="true" role="textbox">my conent</div>`

Anything with `contenteditable="true"` is automatically focusable, and the [role allows](https://www.w3.org/TR/wai-aria-1.1/#textbox) it to have `aria-invalid` and `aria-describedby` attributes.

So the following HTML will cause the screen reader to read something like "Summary, editable text box, invalid [pause] This is required" when the editable area is focused.

```html
<div id="label">Summary</div>
<div contenteditable="true" aria-invalid="true" role="textbox"></div>
<div id="error">This is required</div>
```

Setting the aria attributes is going to Casebooks responsibility.
